- host: terraform-ansible
tasks:
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Feito com terraform e nsible</h1>
  - name: criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &"
